CREATE TABLE CMSUser (
  UserId BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Revision BIGINT UNSIGNED NOT NULL,
  CreatedDate TIMESTAMP NULL,
  LastModifiedDate TIMESTAMP NULL,
  Username VARCHAR(30) NOT NULL UNIQUE,
  Password VARCHAR(100) NOT NULL,
  FullName VARCHAR(100) NOT NULL,
  Role VARCHAR(30) NULL,
  Email VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Article (
  Id VARCHAR(100) NOT NULL PRIMARY KEY,
  PublishedDate TIMESTAMP NULL,
  Author VARCHAR(100) NULL,
  Title VARCHAR(100) NOT NULL,
  Description VARCHAR(100) NULL,
  Keywords VARCHAR(100) NULL
);

