CREATE DATABASE cms DEFAULT CHARACTER SET 'utf8' DEFAULT COLLATE 'utf8_unicode_ci';
CREATE USER 'cmsUser'@'localhost' IDENTIFIED BY 'cmsPassword';
GRANT ALL ON cms.* TO 'cmsUser'@'localhost';

USE cms;

DROP TABLE if EXISTS CMSUser;

CREATE TABLE CMSUser (
  Id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  Version BIGINT UNSIGNED NOT NULL,
  CreatedDate TIMESTAMP NULL,
  LastModifiedDate TIMESTAMP NULL,
  Username VARCHAR(30) NOT NULL UNIQUE,
  Password VARCHAR(100) NOT NULL,
  FullName VARCHAR(100) NOT NULL,
  Role VARCHAR(30) NULL,
  Email VARCHAR(50) NOT NULL UNIQUE
) ENGINE = InnoDB;

DESCRIBE CMSUser;